### PR TITLE
Fix prow build

### PR DESCRIPTION
**Pull request by mstemm**
1. Make build.sh executable so it can be directly invoked from the prow job.
2. Add a pull request template

The below will be a part of the template once merged, this is just to keep poiana happy in the meantime.

```release-note
NONE
```

### CODE REVIEW

**Review by leogr — COMMENTED** [review]
Hey @mstemm 

We have to wait until https://github.com/falcosecurity/test-infra/pull/519 should get merged, then we can retest this PR (hoping it works this time :smile_cat: )

Also, could you remove the PULL_REQUEST_TEMPLATE from here? 
I will just rebase #4 once the job issue has been fixed.

Thank you

**Comment by mstemm** [comment]
Okay, the pull request template is removed in favor of #4.

**Review by leogr — APPROVED** [review]

**Pull request merged**
