### PR TITLE
register new plugin for Seccomp Agent

### PR DESCRIPTION
**Pull request by alban**
Signed-off-by: Alban Crequy <albancrequy@microsoft.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area plugins

> /area registry

> /area build

> /area documentation

**What this PR does / why we need it**:

This PR proposes [a seccomp agent plugin](https://github.com/kinvolk/seccompagent) as new plugin

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

* I used ID 6 because ID 5 will be used by https://github.com/falcosecurity/plugins/pull/69
* The plugin code at https://github.com/falcosecurity/plugins/pull/69 is not yet merged, so I'll leave this PR as draft for now.

cc @rata @Issif

### CODE REVIEW

**Comment by Issif** [comment]
:heart:

**Comment by leogr** [comment]
Hey @alban 

Great job!

Using ID=6 is ok for me and #69 has been merged. So, I'm ready to approve once you rebase this PR :+1:

**Comment by alban** [comment]
@leogr We merged https://github.com/kinvolk/seccompagent/pull/21 and I marked this PR as ready. Thanks!

**Pull request merged**
