### PR TITLE
feat: add more Cloudtrail fields

### PR DESCRIPTION
**Pull request by uhei**
Add more fields as defined at
https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area plugins

**What this PR does / why we need it**:

The current CloudTrail plugin is missing fields. This PR adds all currently defined fields according to [https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-event-reference-record-contents.html).

The fields `ct.addendum.*` and `ct.edgedevicedetails` are untested due to missing events with these fields.

**Special notes for your reviewer**:

The plugin has only been tested with [falcodump](https://www.wireshark.org/docs/man-pages/falcodump.html), [Logray](https://www.wireshark.org/) and CloudTrail access via S3.

### CODE REVIEW

**Comment by leogr** [comment]
cc @Issif

**Comment by leogr** [comment]
cc @Issif @LucaGuerra

**Review by Issif — COMMENTED** [review]
/lgtm

@leogr do you think we should embed the plugin version bump up in that PR too?

**Comment by leogr** [comment]
> /lgtm
> 
> @leogr do you think we should embed the plugin version bump up in that PR too?

I know there should be other planned changes to this plugin, so we can bump up in a later PR.

Btw, the PR SGTM, too. I will do a second look soon and then approve.

Thanks!

**Review by leogr — APPROVED** [review]

**Pull request merged**
