### PR TITLE
chore(build/registry): updated go deps.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area registry

**What this PR does / why we need it**:

Updated go deps and ran `go mod tidy`.
Also, golang for build/registry was bumped to 1.21.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by FedeDP** [comment]
Part of the effort around: https://github.com/falcosecurity/evolution/issues/305

**Comment by FedeDP** [comment]
Registry build is broken now :/
```
make
# github.com/falcosecurity/plugin-sdk-go/pkg/loader
In file included from plugin_loader.c:26:
../../../../go/pkg/mod/github.com/falcosecurity/plugin-sdk-go@v0.7.1/pkg/sdk/strlcpy.h:30:22: error: static declaration of ‘strlcpy’ follows non-static declaration
   30 | static inline size_t strlcpy(char *dst, const char *src, size_t size) {
      |                      ^~~~~~~
In file included from ../../../../go/pkg/mod/github.com/falcosecurity/plugin-sdk-go@v0.7.1/pkg/sdk/strlcpy.h:22:
/usr/include/string.h:506:15: note: previous declaration of ‘strlcpy’ with type ‘size_t(char * restrict,  const char * restrict,  size_t)’ {aka ‘long unsigned int(char * restrict,  const char * restrict,  long unsigned int)’}
  506 | extern size_t strlcpy (char *__restrict __dest,
      |               ^~~~~~~
make: *** [Makefile:25: registry] Error 1
```

**Review by leogr — APPROVED** [review]
Thank you!

**Comment by leogr** [comment]
> Registry build is broken now :/
> 
> ```
> make
> # github.com/falcosecurity/plugin-sdk-go/pkg/loader
> In file included from plugin_loader.c:26:
> ../../../../go/pkg/mod/github.com/falcosecurity/plugin-sdk-go@v0.7.1/pkg/sdk/strlcpy.h:30:22: error: static declaration of ‘strlcpy’ follows non-static declaration
>    30 | static inline size_t strlcpy(char *dst, const char *src, size_t size) {
>       |                      ^~~~~~~
> In file included from ../../../../go/pkg/mod/github.com/falcosecurity/plugin-sdk-go@v0.7.1/pkg/sdk/strlcpy.h:22:
> /usr/include/string.h:506:15: note: previous declaration of ‘strlcpy’ with type ‘size_t(char * restrict,  const char * restrict,  size_t)’ {aka ‘long unsigned int(char * restrict,  const char * restrict,  long unsigned int)’}
>   506 | extern size_t strlcpy (char *__restrict __dest,
>       |               ^~~~~~~
> make: *** [Makefile:25: registry] Error 1
> ```

AFAIK, @jasondellaluce is working on it, right? see https://github.com/falcosecurity/plugins/pull/323

**Pull request merged**
