### PR TITLE
General rules clean up

### LINKED ISSUE #391: Clean up GCP Audit Logs rules file
**Describe the bug**

The rules file for GCP audit logs needs to be cleaned up a bit. There are some weird references to Datadog (maybe they are supposed to be there?), misspelled words, duplicate rules output that don't seem to make sense (A vm has been stopped message when someone updates a VM), and a few grammatical things. 

**How to reproduce it**

Read the rules file :)

**Expected behaviour**

**Screenshots**

**Environment**

**Additional context**

### PR DESCRIPTION
**Pull request by mikegcoleman**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:
/kind cleanup

/area plugins

There were some grammatical errors in the rules themselves. Also some rules output messages were wrong (e.g. it would say "an object was created" when the rule was for deletion). I also separated some rules into two rules - in particular I tried to create "delete" and "modify" rules separately since I think admins would prefer to have more specificity in their output. 

**Which issue(s) this PR fixes**:
Fixes #391 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by leogr** [comment]
Hey @mikegcoleman 

It looks like there're some yaml validation issues. Could you take a look at the failing tests and fix them, please?

For example https://github.com/falcosecurity/plugins/actions/runs/7414200888/job/20294145856?pr=392

**Comment by mikegcoleman** [comment]
@leogr fixed the formatting issues. took a note to run the yaml validator before submitting a PR next time :)

**Comment by leogr** [comment]
> **Major** changes:
> 
> * Rule `GCP IAM serviceAccount key deleted` has been removed
> * Rule `GCP IAM serviceAccount deleted` has been removed
> * Rule `GCP IAM serviceAccount modified` has been removed
> * Rule `GCP backendService deleted` has been removed
> * Rule `GCP IAM serviceAccount created` has been removed
> * Rule `GCP IAM serviceAccount key created` has been removed
> * Rule `GCP IAM principle modified` has been removed
> * Rule `GCP cloud function updated or deleted` has been removed
> * Rule `GCP KMS updated or deleted` has been removed
> * Rule `GCP Pub/Sub Subscriber modified` has been removed

Note for releasers: we can just bump the minor since the major is still `0`
cc @LucaGuerra @Andreagit97 @jasondellaluce

**Review by leogr — APPROVED** [review]
Hey @mikegcoleman 

> @leogr fixed the formatting issues. took a note to run the yaml validator before submitting a PR next time :)

All good now!

Thank you for this PR :clap:

**Pull request merged**
