### PR TITLE
vote: add Issif as owner of the okta plugin for the PR approvals

### PR DESCRIPTION
**Pull request by Issif**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area plugins

> /area registry

> /area build

> /area documentation

**What this PR does / why we need it**:

I'm the developer of this plugin, seems fair to me to be allowed to approve the PR from the community, especially because I'm still continue to develop/answer the issue/review the PR.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by leogr** [comment]
This is a majority vote as [per our governance](https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#voting).

/hold until we get majority or a week has passed

**Comment by leogr** [comment]
and ofc big +1 from me :)

**Comment by jasondellaluce** [comment]
+1 @Issif! Thanks for the help.

**Review by mstemm — APPROVED** [review]
+1 of course!

**Review by leogr — APPROVED** [review]
@Issif We got the majority! :partying_face: 

/hold cancel

**Pull request merged**
