### PR TITLE
add dnscollector plugin

### PR DESCRIPTION
**Pull request by SysdigDan**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area plugins

> /area registry

> /area build

> /area documentation

**What this PR does / why we need it**:
This PR adds a plugin for the dnscollector project (https://github.com/dmachard/go-dnscollector)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by leogr** [comment]
> Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.
> 
> memo **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**
> 
> Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).
> 
> **The list of commits missing DCO signoff**:
> 
> * [be15400](https://github.com/falcosecurity/plugins/commits/be15400f267f72041bfc87b0e088db8efa18411c) add dnscollector plugin

Hey @SysdigDan 

Could you [sign off](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) your commit pls? :pray:

**Comment by SysdigDan** [comment]
Merge commits have been removed.

**Review by leogr — APPROVED** [review]
Hey @SysdigDan 

LGTM now.

PS 
I've just noticed your [repository](https://github.com/SysdigDan/dnscollector-falco-plugin) is missing the LICENSE file. Could you fix it, please? 

Thank you!

**Pull request merged**
