### PR TITLE
chore(cloudtrail): update Go and dependencies

### PR DESCRIPTION
**Pull request by nunoadrego**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area plugins

> /area registry

> /area build

> /area documentation

**What this PR does / why we need it**:

The main goal was to update the `github.com/aws/aws-sdk-go-v2/config` package so that the `AWS_ENDPOINT_URL` env var works.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

The initial discussion started in Kubernetes Falco Slack channel: https://kubernetes.slack.com/archives/CMWH3EH32/p1714641429503799

### CODE REVIEW

**Review by Issif — COMMENTED** [review]
Why didn't you bump up to Go 1.22? Can you also update the plugin version, and the changelog please. Moreover, it also requires to update the versions of Go in the CI, but it could create issues with other plugins.

cc @leogr @jasondellaluce

**Comment by jasondellaluce** [comment]
> Why didn't you bump up to Go 1.22? Can you also update the plugin version, and the changelog please. Moreover, it also requires to update the versions of Go in the CI, but it could create issues with other plugins.
> 
> cc @leogr @jasondellaluce

I think 1.21 is fair enough. The plugin is also a shared Go package, and increasing the required Go version inherently mandates a version bump to adopters importing the plugin's code (other plugins included). This is the rationale by which we always updated the Go version when needed, but to the bare minimum version required. As you see there's also the problem of forcing other plugins to update as well. For now, I'd suggest sticking to 1.21 as proposed in the PR.

**Comment by nunoadrego** [comment]
Suggestions implemented, @Issif.

I generated the changelog by running `./build/changelog/bin/changelog --plugin cloudtrail --from 16306f2` and then checking the commit history and release to see to which they belong. Is there a better way?

**Review by leogr — APPROVED** [review]
Thank you :pray:

**Pull request merged**
