### PR TITLE
Field properties changes

### PR DESCRIPTION
**Pull request by mstemm**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area source-plugins

/area extractor-plugins

> /area build

> /area documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by leogr** [comment]
This PR depends on:
- https://github.com/falcosecurity/libs/pull/167
- https://github.com/falcosecurity/plugin-sdk-go/pull/32

Hold until those get merged.
/hold

**Review by jasondellaluce — COMMENTED** [review]
Can't approve, but LGTM

**Review by leogr — APPROVED** [review]

**Pull request merged**
