### PR TITLE
Bump k8saudit-gke to 0.1.1 to release rules

### PR DESCRIPTION
**Pull request by sboschman**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area plugins

> /area registry

> /area build

> /area documentation

**What this PR does / why we need it**:
Bump k8saudit-gke version to 0.1.1 to trigger the release of a new rules artifact including fix https://github.com/falcosecurity/plugins/commit/e45070ffde9ed6d69c07f25836076ae22aa3ab71

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Issif — COMMENTED** [review]
Could use this PR to create a changelog please

**Comment by sboschman** [comment]
To generate the changelog I made two changes:

- changelog.go
   ```
  // craft a regex to filter all plugin-related dependabot commits
  rgxDeps, _ = regexp.Compile("^[a-f0-9]+ build\\(deps\\):.*" + plugin)
  ```
  
- changelog-gen.sh
  ```
  # generate entry for upcoming tag
  head="$(git rev-parse HEAD)"
  echo "## dev"
  echo ""
  ${tool} --from="" --to=${head} --plugin=${plugin}
  echo ""
   ```
   
   @Issif are these changes useful to add to the plugins repo? If so, I will open a separate PR for it.

**Comment by sboschman** [comment]
@alacuku it seems the `check-version` step does two checks instead of a single one. It runs a check on
`Checking version for rules file "/home/runner/work/plugins/plugins/plugins/k8saudit-gke/rules/k8s_audit_rules.yaml"...`
 
 followed by
 `Checking version for rules file "/home/runner/work/plugins/plugins/plugins/k8saudit-gke/rules/k8s_audit_rules_gke.yaml"...`
 which fails of course as it misses the 'base' k8saudit rules

**Comment by alacuku** [comment]
We did not change anything in that work workflow. Do we have a successful run of that workflow with k8saudit-gke?

**Comment by Issif** [comment]
Seems good on my side, once the CI issue is fixed, we can merge. @alacuku any idea how to fix that dependency issue? I guess it will happen with other plugins

**Comment by Issif** [comment]
> > Seems good on my side, once the CI issue is fixed, we can merge. @alacuku any idea how to fix that dependency issue? I guess it will happen with other plugins
> 
> I'm working on it. The k8saudit-gke added a whole new class of use cases. The issue is related only to this case, it does not affect the existing plugins that have one single rulesfile. 

I agree, l meant if we have plugins for openshift, aks or else, that could happen again. 😉

**Comment by alacuku** [comment]
@sboschman, could you please rebase on #482?

**Comment by sboschman** [comment]
@leogr this pr (and #484 as well) has been rebased

**Review by leogr — APPROVED** [review]

**Pull request merged**
