### PR TITLE
Cloudtrail s3 interval

### PR DESCRIPTION
**Pull request by geraldcombs**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area plugins

> /area registry

> /area build

> /area documentation

**What this PR does / why we need it**:

It should make configuration easier, since you can now just paste in an S3 URL from the AWS console and the plugin will determine which log pathnames need to be downloaded based on specified interval or duration.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jasondellaluce** [comment]
Thanks! Will look into this, but I'm proposing to merge this after we wrap up the new plugins version for the next Falco release (which will happen in the next 2 weeks).

**Comment by jasondellaluce** [comment]
I think the last commit misses a Sign-off!

**Comment by geraldcombs** [comment]
> I think the last commit misses a Sign-off!

Fixed. Thanks!

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
